explicitly use ubuntu:latest in tests
It seems like the version of the ubuntu image that travis happens to grab
doesn't have libcap.so:

not ok 5 everything that gets umoci.json gets foo.mtree as well
(from function `stacker' in file test/helpers.bash, line 31,
 in test file test/intermediate-base-snapshots.bats, line 135)
  `stacker build' failed
initializing stacker recipe: stacker.yaml
stacker build order:
0 build /home/travis/gopath/src/github.com/anuvu/stacker/test/stacker.yaml: requires: []
building: 0 /home/travis/gopath/src/github.com/anuvu/stacker/test/stacker.yaml
building image t1...
importing files...
loading docker://ubuntu
Getting image source signatures
Copying blob sha256:7413c47ba209e555018c4be91101d017737f24b0c9d1f65339b97a4da98acb2a
Copying blob sha256:0fe7e7cbb2e88617d969efeeb3bd3125f7d309335c736a0525233ec2dc06aee1
Copying blob sha256:1d425c98234572d4221a1ac173162c4279f9fdde4726ec22ad3c399f59bb7503
Copying blob sha256:344da5c95cecd0f55238ce59b8469ee301056001ece2b769e9691b80f94f9f37
Copying config sha256:5f40de30a14521a4e532d4a73021d2efe54e26309406841f266a4ebf52508528
Writing manifest to image destination
Storing signatures
unpacking to /home/travis/gopath/src/github.com/anuvu/stacker/test/roots/_working
running commands...
running commands for t1
lxc-init: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory
error: run commands failed: execute failed: exit status 127

ubuntu:latest works fine in the test right above this one (and this test
passes locally for me...), so hopefully this fixes things.

Signed-off-by: Tycho Andersen <tycho@tycho.ws>