test/caching: modify the layer between bind builds
see comment, we get a stack trace like

error: rename /home/tycho/stacker/stackertest-test_bind_rebuilds.9PrnFF/roots/bind-test/overlay /home/tycho/stacker/stackertest-test_bind_rebuilds.9PrnFF/roots/sha256_3c27455941af66e07bfb281bd7b489b54a91ce8ca63
f8f52466679d77ef2c8/overlay: file exists
couldn't move overlay data to new location
github.com/anuvu/stacker/overlay.generateLayer
      /home/tycho/stacker/overlay/pack.go:395
github.com/anuvu/stacker/overlay.RepackOverlay
      /home/tycho/stacker/overlay/pack.go:471
main.doRepackOverlay
      /home/tycho/stacker/cmd/umoci.go:455
github.com/urfave/cli.HandleAction
      /home/tycho/packages/go/pkg/mod/github.com/urfave/cli@v1.22.5-0.20200826140443-af7fa3de115a/app.go:524
github.com/urfave/cli.Command.Run
      /home/tycho/packages/go/pkg/mod/github.com/urfave/cli@v1.22.5-0.20200826140443-af7fa3de115a/command.go:173
github.com/urfave/cli.(*App).RunAsSubcommand
      /home/tycho/packages/go/pkg/mod/github.com/urfave/cli@v1.22.5-0.20200826140443-af7fa3de115a/app.go:405
github.com/urfave/cli.Command.startApp
      /home/tycho/packages/go/pkg/mod/github.com/urfave/cli@v1.22.5-0.20200826140443-af7fa3de115a/command.go:372
github.com/urfave/cli.Command.Run
      /home/tycho/packages/go/pkg/mod/github.com/urfave/cli@v1.22.5-0.20200826140443-af7fa3de115a/command.go:102
github.com/urfave/cli.(*App).Run
      /home/tycho/packages/go/pkg/mod/github.com/urfave/cli@v1.22.5-0.20200826140443-af7fa3de115a/app.go:277
main.main
      /home/tycho/stacker/cmd/main.go:204
runtime.main
      /usr/local/go/src/runtime/proc.go:203
runtime.goexit
      /usr/local/go/src/runtime/asm_amd64.s:1373
error: exit status 1

This commit also removes the `out' file, since we can just use bats'
$output variable to inspect the command output.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>