storage: add a locking mechanism
stacker is not threadsafe (process-safe?), so let's lock use some advisory
locking to avoid running two stackers at the same time. This results in
error messages like:

error: resource temporarily unavailable
couldn't acquire lock on /home/user/packages/stacker/stackertest-test_two_stackers_can-27t_run_at_the_same_time.n97E26/roots/.lock: lock owned by pid 350804

Note that we are extra paranoid here: we lock both the stacker dir, and the
roots dir, in case someone has diverged in their usage. This suggests maybe
we should just get rid of --roots-dir at some point in the future.

Because of locking the roots dir, in the btrfs backend we have to start
using DETACH mounts when we detach/clean the storage. We could of course
unlock before unmounting, but that leaves us open to a race on the
storage if someone locks again between our unlock and unmount.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>