test: skip chmod 000 test in travis
Fails with:

not ok 56 file with chmod 000 works
(in test file test/unprivileged.bats, line 30)
  `sudo -u $SUDO_USER "${ROOT_DIR}/stacker" build' failed
stacker version 620cacf4c9962976b25a6e45119efd7c82a13578
preparing image parent...
loading docker://centos:latest
lxc 20200713181949.654 ERROR    conf - conf.c:write_id_mapping:2646 - Operation not permitted - Failed to write uid mapping to "/proc/20864/uid_map"
lxc 20200713181949.654 ERROR    conf - conf.c:lxc_map_ids:2822 - Failed to write mapping: 0 2000 1
1 100001 65535
Failed to write id mapping for child process
lxc 20200713181949.654 ERROR    utils - utils.c:lxc_setgroups:1363 - Operation not permitted - Failed to setgroups()
error: image unpack failed: exit status 1

presumably because we're not doing the nested containers stuff quite right
somehow.

Signed-off-by: Tycho Andersen <tycho@tycho.ws>