fix: use a umoci which has fix for another empty lgetxattr (#586)
We end up with errors like:

/home/shallyn/stackertest2/roots/test2/overlay/etc/systemd/system/multi-user.target.wants: dropped overlay attrs: user.overlay.origin
error: no data available
get xattr: user.overlay.origin
github.com/opencontainers/umoci/oci/layer.(*tarGenerator).AddFile
        /stacker-tree/.build/gopath/pkg/mod/github.com/project-stacker/umoci@v0.0.0-20231025233220-c7bb24d57e98/oci/layer/tar_generate.go:225
github.com/opencontainers/umoci/oci/layer.GenerateInsertLayer.func1.2

Unless there is an actual data i/o error, ignore it.  In particular,
if the fs either says eopnotsupp, enodata, or eperm, just assume the
xattr did not actually exist.  We have to do this because there are
cases where listxattr will return xattr keys which getxattr will filter
out, and we're expected to ignore those.

Signed-off-by: Serge Hallyn <shallyn@cisco.com>