try to fix CI
We are getting:

E: The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Release' no longer has a Release file.
Error: Process completed with exit code 100.

although we no longer depend on this repo (we used to to import skopeo, but
e869c8138f6f ("ci/tests: move away from skopeo") removed that.

Seems like github is caching things, so let's try to clear the cache.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>