ci: don't use LXC ppa
We're getting what are presumably temporary failures:

Run sudo add-apt-repository -y ppa:ubuntu-lxc/lxc-git-master
Cannot add PPA: 'ppa:~ubuntu-lxc/ubuntu/lxc-git-master'.
ERROR: '~ubuntu-lxc' user or team does not exist.

but also since we're statically linking the final binary, this (hopefully)
doesn't matter.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>