ci(convert): add missing substitute var
"""
cache miss because layer definition was changed
error: layer needs to be rebuilt before publishing: alpine
error: exit status 1
"""

Signed-off-by: Ramkumar Chinchani <rchincha@cisco.com>