cache: bump cache version + add some tests
If we run the test/caching.bats test with:

diff --git a/test/caching.bats b/test/caching.bats
index b2091d2..bbb0b20 100644
--- a/test/caching.bats
+++ b/test/caching.bats
@@ -185,7 +185,7 @@ EOF

 @test "can read previous version's cache" {
     git clone https://github.com/anuvu/stacker
-    (cd stacker && make)
+    (cd stacker && git co 481c315c8ca3c930fb8a215df8baf0b06bc38bc7 && make)

     # note that this is not quite a complete test: since the cache has a
     # types.Layer in it, anything that can change in there could break this. so

we get:

error: json: cannot unmarshal string into Go struct field Layer.cache.Layer.Import of type types.Import

This is because the commit after 481c315, 60cb730340ac ("Support
specifying hash of import source, closes #119") changed the cache
structure. We have a provision when the cache structure is changed: bump
the cache version so that things are completely invalidated and totally
rebuilt. However, this change snuck through without getting a cache version
bump. So, let's bump it now.

There's another caching test with the hardcoded zero-value hash for
CacheEntry that should catch any future changes to this structure.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>