cache: don't hash, use reflect.DeepEqual() for layer comparisons
We have reports of the following failure:

...
Dependency Order [rootfs atomix-rootfs-pkg atomix-rootfs]
...
found cached layer rootfs-squashfs
found cached layer rootfs
preparing image atomix-rootfs-pkg...
...
cache miss because layer definition was changed
error: couldn't find a cache of base layer for atomix-rootfs-pkg: rootfs
github.com/anuvu/stacker.(*BuildCache).getBaseHash
	/stacker-tree/cache.go:359
github.com/anuvu/stacker.(*BuildCache).Put
	/stacker-tree/cache.go:409
github.com/anuvu/stacker.(*Builder).Build
	/stacker-tree/build.go:490
github.com/anuvu/stacker.(*Builder).BuildMultiple
	/stacker-tree/build.go:578
main.doRecursiveBuild
	/stacker-tree/cmd/recursive-build.go:69
github.com/urfave/cli.HandleAction
	/stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524
github.com/urfave/cli.Command.Run
	/stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173
github.com/urfave/cli.(*App).Run
	/stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277
main.main
	/stacker-tree/cmd/main.go:302
runtime.main
	/usr/lib/go/src/runtime/proc.go:255
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1581
error: exit status 1
main.main.func3
	/stacker-tree/cmd/main.go:295
github.com/urfave/cli.(*App).Run
	/stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:264
main.main
	/stacker-tree/cmd/main.go:302
runtime.main
	/usr/lib/go/src/runtime/proc.go:255
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1581

I think that what's going on here is that something weird is happening with the
structure hashing. It turns out we don't really need a hash, we just need
equality, so let's simplify the calculation and hopefully fix the bug.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>